apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
spec:
  releaseName: prometheus-operator
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "13.13.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      ingress:
        enabled: false
