apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  values:
    prometheus:
      prometheusSpec:
        replicas: 3
        retention: 30d
